deepspeech:
  adminRoles:
    - github-team:mozilla/research-machine-learning
  repos:
    - github.com/mozilla/DeepSpeech:*
    - github.com/mozilla/tensorflow:*
  workerPools:
    ci:
      owner: deepspeech@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 96
      machineType: "zones/{zone}/machineTypes/n1-standard-32"
    win:
      owner: deepspeech@mozilla.com
      emailOnError: false
      imageset: deepspeech-win2012r2
      cloud: aws
      instanceTypes:
        m5d.2xlarge: 1
      maxCapacity: 16
    win-b:
      owner: deepspeech@mozilla.com
      emailOnError: false
      imageset: deepspeech-win2012r2
      cloud: aws
      instanceTypes:
        m5d.2xlarge: 1
      maxCapacity: 16
  clients:
    worker/rpi3bp-1:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-2:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-3:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-4:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-5:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/rpi3bp-6:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-rpi3-*
        - assume:worker-pool:proj-deepspeech/ds-rpi3
    worker/lepotato-1:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-2:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-3:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-4:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-5:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/lepotato-6:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-lepotato-*
        - assume:worker-pool:proj-deepspeech/ds-lepotato
    worker/macos-heavy-1:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-heavy-*
        - assume:worker-pool:proj-deepspeech/ds-macos-heavy
    worker/macos-heavy-2:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-heavy-*
        - assume:worker-pool:proj-deepspeech/ds-macos-heavy
    worker/macos-heavy-3:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-heavy-*
        - assume:worker-pool:proj-deepspeech/ds-macos-heavy
    worker/macos-heavy-4:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-heavy-*
        - assume:worker-pool:proj-deepspeech/ds-macos-heavy
    worker/macos-light-1:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-2:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-3:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-4:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-5:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-6:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-7:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-8:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-9:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-10:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-11:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/macos-light-12:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-macos-light-*
        - assume:worker-pool:proj-deepspeech/ds-macos-light
    worker/pkguploader:
      scopes:
        - assume:worker-id:proj-deepspeech/ds-scriptworker-*
        - assume:worker-pool:proj-deepspeech/ds-scriptworker
  grants:
    - grant:
        - queue:create-task:highest:proj-deepspeech/*
        # decision task:
        # https://github.com/mozilla/tensorflow/blob/master/tc-schedule.sh
        # =>
        # https://github.com/lissyx/taskcluster-github-decision/blob/master/tc-decision.py
        - queue:scheduler-id:taskcluster-github
        - queue:route:index.project.deepspeech.*
        - index:insert-task:project.deepspeech.*
        - queue:route:notify.irc-channel.*
        - generic-worker:cache:deepspeech-*
      to:
        - repo:github.com/mozilla/DeepSpeech:*
        - repo:github.com/mozilla/tensorflow:*
    - grant:
        - generic-worker:allow-rdp:proj-deepspeech/*
      to:
        - project-admin:deepspeech
  secrets:
    ssh-keys/deepspeech-win: true
    ssh-keys/deepspeech-win-b: true
