fuzzing:
  adminRoles:
    - github-team:MozillaSecurity/tc-admin
  externallyManaged: true # Fuzzing hooks are deployed through another repo
  repos:
    - github.com/MozillaSecurity/*
  secrets:
    codecov-fuzzfetch: true
    codecov-fuzzmanager: true
    credstash-aws-auth: true
    deploy-bearspray: true
    deploy-fuzzing-tc-config: true
    deploy-octo-private: true
    docker-hub: true
    pypi: true
    decision: true
  workerPools:
    ci:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: docker-worker
      cloud: gcp
      minCapacity: 0
      maxCapacity: 10
    generic-worker-ubuntu-18-04-podman:
      owner: fuzzing+taskcluster@mozilla.com
      emailOnError: false
      imageset: generic-worker-ubuntu-18-04-podman
      cloud: aws
      minCapacity: 0
      maxCapacity: 10

  grants:
    - grant:
        - queue:create-task:highest:proj-fuzzing/ci
        - secrets:get:project/fuzzing/deploy-*
        - secrets:get:project/fuzzing/codecov-*
        - secrets:get:project/fuzzing/pypi
        - secrets:get:project/fuzzing/ci-*
      to:
        - repo:github.com/MozillaSecurity/*
    - grant:
        - docker-worker:capability:privileged
        - queue:route:index.project.fuzzing.config.*
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc:*
    - grant:
        - secrets:get:project/fuzzing/decision
        - secrets:get:project/fuzzing/deploy-*
        - secrets:get:project/fuzzing/credstash-aws-auth
      to:
        - repo:github.com/MozillaSecurity/fuzzing-tc-config:*

    # fuzzing-tc-config code on master can run tc-admin apply to manage worker pools
    - grant:
       - worker-manager:manage-worker-pool:proj-fuzzing/*
       - worker-manager:provider:community-tc-workers-*
      to:
       - repo:github.com/MozillaSecurity/fuzzing-tc-config:branch:master
